---
  - name: Install Wireguard on server
    hosts: all
    tasks:
      - name: Update apt packages
        apt: upgrade=yes update_cache=yes
        when: ansible_facts['os_family'] == "Debian"
      - name: Ensure wireguard and basic system packages are installed
        apt:
          pkg:
            - wireguard
            - resolvconf
          state: present
      - name: Set sysctl to forward IP traffic
        blockinfile:
          path: /etc/sysctl.conf
          block: |
            net.ipv4.ip_forward=1
      - name: Enable WireGuard kernel module
        modprobe:
          name: wireguard
          state: present
        register: wireguard_module_enabled
        until: wireguard_module_enabled is succeeded
        retries: 10
        delay: 10
        failed_when: wireguard_module_enabled is failure
      - name: Reboot machine to pick up changes
        reboot:
          reboot_timeout: 120
